In [10]:
import torch
import torch.nn as nn

张量的创建和操作

In [14]:
# 初始化的值为随机
a = torch.empty(5,3)
a

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 1.6087e-42, 0.0000e+00],
        [0.0000e+00, 4.6838e-39, 0.0000e+00]])

初始化

In [18]:
nn.init.zeros_(a) # 初始化为0
nn.init.ones_(a)  # 初始化为1
nn.init.uniform_(a)  # 初始化为uniform分布（均匀分布）

tensor([[0.9563, 0.8501, 0.0944],
        [0.2881, 0.0948, 0.7249],
        [0.0176, 0.2453, 0.1849],
        [0.1737, 0.9555, 0.5033],
        [0.4842, 0.1812, 0.5842]])

随机数矩阵

In [21]:
m = torch.rand(5, 3)              # 5*3 ， [0, 1)的随机数

In [22]:
torch.rand_like(m)            #创建和m的size一样的随机数矩阵

tensor([[0.9818, 0.9834, 0.6669],
        [0.7722, 0.9811, 0.9620],
        [0.8457, 0.9276, 0.4500],
        [0.8454, 0.7010, 0.5747],
        [0.4654, 0.9291, 0.9343]])

In [23]:
new_tensor = torch.Tensor([[1,2,3],[2,4,5]])
new_tensor

tensor([[1., 2., 3.],
        [2., 4., 5.]])

In [25]:
print_method = [new_tensor.shape,
                new_tensor.size(), 
                new_tensor.dtype]
for i in print_method:
    print(i)     

torch.Size([2, 3])
torch.Size([2, 3])
torch.float32


In [28]:
new_tensor_copy = torch.ones_like(new_tensor, dtype=torch.int16)
new_tensor_copy

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)

## reshape

In [31]:
new_tensor_copy.view(-1,6)

tensor([[1, 1, 1, 1, 1, 1]], dtype=torch.int16)

Tensor与numpy.array()的相互转换

In [32]:
new_tensor_copy

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)

In [33]:
type(new_tensor_copy)

torch.Tensor

In [34]:
torch_to_numpy = new_tensor_copy.numpy()
print(type(torch_to_numpy))
torch_to_numpy

<class 'numpy.ndarray'>


array([[1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [35]:
torch_to_numpy.shape

(2, 3)

In [36]:
numpy_to_tensor = torch.from_numpy(torch_to_numpy)
print(type(numpy_to_tensor))
numpy_to_tensor

<class 'torch.Tensor'>


tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)

### 张量的索引，切片

In [38]:
tensor = torch.rand(4,5)
tensor

tensor([[0.1750, 0.2051, 0.0636, 0.1919, 0.0299],
        [0.1440, 0.5942, 0.2117, 0.6135, 0.1671],
        [0.1822, 0.7726, 0.4616, 0.8800, 0.1770],
        [0.9412, 0.2084, 0.9316, 0.9052, 0.4798]])

In [39]:
print(tensor[:2,:])

tensor([[0.1750, 0.2051, 0.0636, 0.1919, 0.0299],
        [0.1440, 0.5942, 0.2117, 0.6135, 0.1671]])


In [41]:
tensor[tensor > 0.1].shape

torch.Size([18])

In [57]:
tensor.view(-1).shape

torch.Size([20])

In [48]:
tensor_on_item = torch.Tensor([1])
tensor_on_item.item()

1.0

### 自动求导

autograd package是PyTorch中所有神经网络的核心。先了解一些基本知识，然后开始训练第一个神经网络。autograd package提供了Tensors上所有运算的自动求导功能。它是一个按运行定义（define-by-run）的框架，这意味着反向传播是依据代码运行情况而定义的，并且每一个单次迭代都可能不相同。

### 1.变量
autograd.Variable是这个package的中心类。它打包了一个Tensor，并且支持几乎所有运算。一旦你完成了你的计算，可以调用.backward()，所有梯度就可以自动计算。  
你可以使用.data属性来访问原始tensor。相对于变量的梯度值可以被积累到.grad中。  
这里还有一个类对于自动梯度的执行是很重要的：Function（函数）
变量和函数是相互关联的，并且建立一个非循环图。每一个变量有一个.grad_fn属性，它可以引用一个创建了变量的函数（除了那些用户创建的变量——他们的grad_fn是空的）。  
如果想要计算导数，可以调用Variable上的.backward()。如果变量是标量（只有一个元素），你不需要为backward()确定任何参数。但是，如果它有多个元素，你需要确定grad_output参数（这是一个具有匹配形状的tensor）。

In [58]:
from torch.autograd import Variable

In [70]:
# #设置requires_grad=True， backward时会计算导数
x = Variable(torch.ones(2,2), requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [71]:
y = x+2
out = y.mean()
out.backward()
x.grad

tensor([[0.2500, 0.2500],
        [0.2500, 0.2500]])