In [1]:
import torch

In [2]:
# torch.FloatTensor()
# torch.LongTensor()
# torch.IntTensor()
# torch.ShortTensor()
a = torch.LongTensor([[1,2]])
a

tensor([[1, 2]])

In [12]:
b = torch.FloatTensor([1,2]).long()
b

tensor([1, 2])

In [17]:
a = torch.rand(2,3)
print("a:\n", a)
print(a.type(torch.LongTensor))
print(a)

a:
 tensor([[0.6904, 0.6105, 0.7585],
        [0.3313, 0.6810, 0.9443]])
tensor([[0, 0, 0],
        [0, 0, 0]])
tensor([[0.6904, 0.6105, 0.7585],
        [0.3313, 0.6810, 0.9443]])


## cuda/cpu/

如果没有特别说明：tensor是cpu上的变量  
使用gpu张量：tensor.cuda()  
使用cpu张量：tensor.cpu()

In [30]:
a = torch.ones(2,2,3)
print(a)
a.size()

tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])


torch.Size([2, 2, 3])

In [33]:
device = torch.device('cuda:' + '0' if torch.cuda.is_available() else 'cpu')
print("device:\t", device)

device:	 cpu


In [34]:
a.to(device)

tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])

TypeError: new() received an invalid combination of arguments - got (list, requires_grad=bool), but expected one of:
 * (torch.device device)
 * (torch.Storage storage)
 * (Tensor other)
 * (tuple of ints size, torch.device device)
      didn't match because some of the keywords were incorrect: requires_grad
 * (object data, torch.device device)
      didn't match because some of the keywords were incorrect: requires_grad
